experiment:
  log_path: ./runs/cat
  cuda: cuda:0
  randomseed: 42
  start_epoch: 1
  end_epoch: 2000
  batch_size: 8 * 1
  save_every_epoch: 500
  eval_every_iter: 50

dataset:
  data_path: ./data/cat
  gray_scale: false
  shadow_threshold: 0.1
  sparse_input: null
  sparse_input_random_seed: null

models:
  load_checkpoint: false
  checkpoint_path: null
  use_mean_var: true
  use_onlydiffuse: false
  use_onlyspecular: false

  nerf:
    num_layers: 8
    hidden_size: 256
    skip_connect_every: 3
    num_encoding_fn_input1: 10
    num_encoding_fn_input2: 0
    include_input_input1: 2
    include_input_input2: 0

  specular:
    type: Spherical_Gaussian
    num_basis: 12
    k_low: 10
    k_high: 300
    trainable_k: true
    dynamic_basis: true

  light_model:
    type: Light_Model_CNN
    explicit_direction: true
    explicit_intensity: true
    num_layers: 3
    hidden_size: 64
    skip_connect_every: 8
    load_pretrain: runs/pre_trained_LNet/model_params.pth
    ld_noise: 0
    li_noise: 0

loss:
  rgb_loss: l1
  spec_coeff_factor: 0.0
  diff_tv_factor: 0.01
  spec_tv_factor: 0.01
  normal_tv_factor: 0.01
  contour_factor: 0.1
  regularize_epoches: 0.25

optimizer:
  lr: 0.001
  type: Adam

scheduler:
  step_size: 500000
  gamma: 1
