name: scps_nir
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=2.0.1
  - torchvision=0.15.2
  - cudatoolkit=11.8
  - tensorboard
  - scipy
  - scikit-image
  - opencv-python-headless
  - pip
  - pip:
    - matplotlib
